import Head from "next/head";


import LoadMore from "../components/LoadMore/LoadMore";
import Nav from "../components/Nav/Nav";
import SearchBar from "../components/SearchBar/SearchBar";
import Table from "../components/Table/Table";
import Text from "../components/Text";

import Pagination from "../components/Pagination/PaginationNav";
import { useContext, useEffect } from "react";
import dataContext from "../context/dataContext";

const Layout = ():JSX.Element => {
  const {isLoading} = useContext(dataContext);

  useEffect(() => {
    
  }, [isLoading])
  
  return (
        <div className={``}>
          <Head>
            <title>Pharma Inc.</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
          </Head>
          <Nav />
          <div
            className={`flex flex-col flex-nowrap place-items-center w-2/4 mx-auto mt-16`}
          >
            <Text />
            <SearchBar />
            <Table />
            <LoadMore />

          </div>
        </div>
  );
};

export default Layout;
